// Generated by CoffeeScript 2.7.0
(function() {
  //Best in Chrome, Safari - Firefox has some glitchy control issues.
  $(function() {
    var end_movement, mario, move_degree, move_mario, move_times, start_movement, window_width, x_movement, x_movement_dir, x_movement_on, y_movement;
    mario = {
      element: $('.mario'),
      bottom: 40,
      left: 100
    };
    move_times = 10;
    x_movement = null;
    x_movement_on = false;
    x_movement_dir = 0;
    y_movement = null;
    window_width = $(window).width();
    move_degree = function(d) {
      return d * move_times;
    };
    move_mario = function(x, y) {
      var new_x, new_y;
      new_x = mario.left + x;
      if (new_x < 5) {
        new_x = 5;
      }
      new_y = mario.bottom + y;
      if (new_y < 40) {
        new_y = 40;
      }
      mario.bottom = new_y;
      mario.left = new_x;
      return mario.element.css({
        bottom: mario.bottom,
        left: mario.left
      });
    };
    start_movement = function(x, y) {
      // allow rapid change of direction
      if (x !== 0 && x_movement_on && x_movement_dir !== x) {
        end_movement('x');
      }
      if (x !== 0 && !x_movement_on) {
        if (x < 0) {
          mario.element.addClass('left');
        }
        if (x > 0) {
          mario.element.addClass('right');
        }
        x_movement_dir = x;
        x_movement = setInterval(function() {
          return move_mario(move_degree(x), 0);
        }, 100);
        return x_movement_on = true;
      } else if (y !== 0) {
        return y_movement = setInterval(function() {
          return move_mario(0, move_degree(y));
        }, 100);
      }
    };
    end_movement = function(axis) {
      if (axis === 'x') {
        mario.element.removeClass('left');
        mario.element.removeClass('right');
        clearInterval(x_movement);
        return x_movement_on = false;
      } else if (axis === 'y') {
        return clearInterval(y_movement);
      }
    };
    $(window).keydown(function(e) {
      if (e.which === 65 || e.which === 37) {
        return start_movement(-4, 0);
      } else if (e.which === 68 || e.which === 39) {
        return start_movement(4, 0);
      } else if (e.which === 32) {
        if (mario.bottom === 40) { // must be on the ground to jump
          return move_mario(0, move_degree(20));
        }
      }
    });
    $(window).keyup(function(e) {
      // only stop the animation if the current movement matches that of the button being released, if a change of direction had happened, we want to ignore this button release
      if (e.which === 65 || e.which === 37) {
        if (!(x_movement_dir > 0)) {
          return end_movement('x');
        }
      } else if (e.which === 68 || e.which === 39) {
        if (!(x_movement_dir < 0)) {
          return end_movement('x');
        }
      }
    });
    return setInterval(function() {
      if (mario.bottom !== 40) { // gravity
        return move_mario(0, move_degree(-2));
      }
    }, 40);
  });

}).call(this);
